"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUp, Bell, BookOpen, BarChart3, Check, ChevronRight, Command, Database, FileText, History, LayoutDashboard, Menu, Moon, Plus, Search, Settings2, Sparkles, Sun, X } from "lucide-react";
import ChatUI from "@/components/ChatUI";

type View = "Dashboard" | "Analyses" | "Workflows" | "Insights" | "Alerts" | "Reports" | "Data" | "Settings";
type Audience = "Executive" | "Analyst" | "Operator";

const nav: { label: View; icon: typeof LayoutDashboard }[] = [
  { label: "Dashboard", icon: LayoutDashboard }, { label: "Analyses", icon: BarChart3 }, { label: "Workflows", icon: Sparkles },
  { label: "Insights", icon: BookOpen }, { label: "Alerts", icon: Bell }, { label: "Reports", icon: FileText }, { label: "Data", icon: Database },
];
const suggestions = ["Analyze brand performance across retailers.", "Find unusual changes in sales.", "Evaluate promotion effectiveness.", "Identify distribution opportunities."];
const workflowCards = [{ title: "Brand performance review", detail: "Compare growth, velocity, and share across retailers." }, { title: "Promotion effectiveness", detail: "Understand lift, depth, and where campaigns softened." }, { title: "Distribution opportunity", detail: "Find whitespace across channels and regions." }, { title: "Demand forecast", detail: "Project next-period demand from connected data." }];

export function CPGistWorkspace({ initialView = "Dashboard" as View }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView);
  const [query, setQuery] = useState("");
  const [audience, setAudience] = useState<Audience>("Executive");
  const [running, setRunning] = useState(false);
  const [dark, setDark] = useState(true);
  const [sidebar, setSidebar] = useState(false);
  const [commands, setCommands] = useState(false);
  const [alerts, setAlerts] = useState(0);

  useEffect(() => { const saved = window.localStorage.getItem("cpgist-theme"); if (saved) setDark(saved === "dark"); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; window.localStorage.setItem("cpgist-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { fetch("/api/alerts").then((r) => r.ok ? r.json() : null).then((data) => { const rows = Array.isArray(data) ? data : data?.alerts ?? []; setAlerts(rows.filter((row: { read?: boolean }) => !row.read).length); }).catch(() => undefined); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommands(true); } if (event.key === "Escape") { setCommands(false); setSidebar(false); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);

  const title = useMemo(() => view === "Dashboard" ? "Good morning, Mohanraj." : view, [view]);
  function go(next: View) { setView(next); setSidebar(false); }
  function assign(text = query) { if (!text.trim()) return; setQuery(text); setRunning(true); setView("Analyses"); setSidebar(false); }
  function reset() { setQuery(""); setRunning(false); setView("Dashboard"); }

  return <div className="min-h-screen bg-[var(--background)] text-[var(--text-primary)]">
    <header className="sticky top-0 z-30 border-b border-[var(--border)] bg-[var(--background)]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8">
      <div className="flex items-center gap-3"><button className="rounded-lg p-2 lg:hidden" aria-label="Open navigation" onClick={() => setSidebar(true)}><Menu size={19}/></button><button onClick={reset} className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-[var(--accent)] text-[var(--background)]"><Sparkles size={16}/></span><span className="font-semibold tracking-tight">CPGist</span></button><span className="hidden text-xs text-[var(--text-muted)] sm:block">AI retail analyst</span></div>
      <div className="flex items-center gap-1"><button onClick={() => setCommands(true)} className="hidden items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 text-xs text-[var(--text-secondary)] md:flex"><Command size={14}/> Search <kbd>⌘K</kbd></button><button aria-label="Toggle theme" onClick={() => setDark(!dark)} className="rounded-lg p-2 text-[var(--text-secondary)]">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button aria-label="Alerts" onClick={() => go("Alerts")} className="relative rounded-lg p-2 text-[var(--text-secondary)]"><Bell size={18}/>{alerts > 0 && <i className="absolute right-1 top-1 size-1.5 rounded-full bg-[var(--warning)]"/>}</button><span className="grid size-8 place-items-center rounded-full border border-[var(--accent)]/40 text-xs text-[var(--accent)]">MR</span></div>
    </div></header>
    <div className="mx-auto flex max-w-[1500px]">
      <aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r border-[var(--border)] bg-[var(--surface)] px-4 pt-20 transition-transform lg:sticky lg:top-16 lg:block lg:h-[calc(100vh-4rem)] lg:translate-x-0 lg:bg-transparent lg:px-5 lg:pt-7 ${sidebar ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-7 flex justify-between lg:hidden"><b>Workspace</b><button aria-label="Close navigation" onClick={() => setSidebar(false)}><X size={18}/></button></div><button onClick={() => reset()} className="mb-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-3 py-3 text-xs font-semibold text-[var(--background)]"><Plus size={15}/> New analysis</button><p className="mb-3 px-2 text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--text-muted)]">Workspace</p><nav className="space-y-1" aria-label="Workspace navigation">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => go(label)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${view === label ? "bg-[var(--accent-soft)] font-medium text-[var(--accent)]" : "text-[var(--text-secondary)] hover:bg-[var(--surface-secondary)]"}`}><Icon size={17}/>{label}{label === "Alerts" && alerts > 0 && <span className="ml-auto text-[10px] text-[var(--warning)]">{alerts}</span>}</button>)}</nav><div className="my-7 h-px bg-[var(--border)]"/><button onClick={() => go("Settings")} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[var(--text-secondary)]"><Settings2 size={17}/>Settings</button></aside>
      {sidebar && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-black/50 lg:hidden" onClick={() => setSidebar(false)}/>}<main className="min-w-0 flex-1 px-4 pb-20 pt-8 sm:px-8 lg:px-14 lg:pt-12">{view === "Dashboard" ? <Dashboard assign={assign} query={query} setQuery={setQuery} audience={audience} setAudience={setAudience}/> : view === "Analyses" ? <Analysis query={query} running={running} reset={reset}/> : view === "Workflows" ? <Workflows assign={assign}/> : <Placeholder view={view} go={go} alerts={alerts}/>}</main></div>
    {commands && <div className="fixed inset-0 z-50 bg-black/60 px-4 pt-24" onClick={() => setCommands(false)}><div className="mx-auto max-w-lg overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex gap-3 border-b border-[var(--border)] p-4"><Search size={17}/><input autoFocus placeholder="Search CPGist" className="flex-1 bg-transparent text-sm outline-none" onKeyDown={(e) => e.key === "Escape" && setCommands(false)}/></div><button onClick={() => { setCommands(false); reset(); }} className="flex w-full gap-3 p-4 text-left text-sm hover:bg-[var(--surface-secondary)]"><Plus size={16}/> New analysis</button></div></div>}
  </div>;
}

function Dashboard({ assign, query, setQuery, audience, setAudience }: { assign: (text?: string) => void; query: string; setQuery: (v: string) => void; audience: Audience; setAudience: (v: Audience) => void }) { return <section className="mx-auto max-w-5xl animate-fade-up"><div className="mb-12 max-w-2xl"><p className="eyebrow mb-4">Business intelligence workspace</p><h1 className="font-serif text-4xl tracking-[-.04em] sm:text-6xl">Good morning, Mohanraj.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[var(--text-secondary)]">Here is where you assign work to your analyst and turn connected retail data into decisions.</p></div><div className="mb-10 grid gap-3 sm:grid-cols-2"><Attention label="Needs attention" value="No alert data available" detail="Connect a dataset to surface business changes."/><Attention label="Data status" value="Awaiting source" detail="Your analysis will show real metrics once data is available."/></div><div className="rounded-2xl border border-[var(--accent)]/30 bg-[var(--surface)] p-3 shadow-2xl"><div className="px-3 py-2"><span className="eyebrow">Assign analytical work</span><textarea value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); assign(); } }} rows={4} placeholder="What should your analyst investigate?" className="mt-3 w-full resize-none bg-transparent text-lg leading-8 outline-none placeholder:text-[var(--text-muted)]"/></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] px-3 pt-3"><span className="text-xs text-[var(--text-muted)]">Source-traceable answers · Shift + Enter for a new line</span><div className="flex items-center gap-2"><select value={audience} onChange={(e) => setAudience(e.target.value as Audience)} aria-label="Audience" className="rounded-lg border border-[var(--border)] bg-transparent px-2 py-2 text-xs"><option>Executive</option><option>Analyst</option><option>Operator</option></select><button disabled={!query.trim()} onClick={() => assign()} className="flex items-center gap-2 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-[var(--background)] disabled:opacity-40">Run analysis <ArrowUp size={14}/></button></div></div></div><div className="mt-5 flex flex-wrap gap-2">{suggestions.map((item) => <button key={item} onClick={() => assign(item)} className="rounded-full border border-[var(--border)] px-3 py-2 text-xs text-[var(--text-secondary)] hover:border-[var(--accent)]">{item}</button>)}</div></section> }
function Attention({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><span className="eyebrow">{label}</span><h2 className="mt-5 text-sm font-semibold">{value}</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{detail}</p></div> }
function Analysis({ query, running, reset }: { query: string; running: boolean; reset: () => void }) { return <section className="mx-auto max-w-6xl animate-fade-up"><div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><span className="eyebrow">Analysis session</span><h1 className="mt-3 max-w-3xl font-serif text-3xl sm:text-5xl">{query || "New analysis"}</h1><div className="mt-4 flex items-center gap-2 text-xs text-[var(--text-secondary)]"><span className="size-2 rounded-full bg-[var(--success)]"/>{running ? "Ready to run against connected data" : "Complete"}</div></div><button onClick={reset} className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs">New analysis</button></div><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-5"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><span className="eyebrow">Executive summary</span><p className="mt-5 text-lg leading-8 text-[var(--text-secondary)]">Analysis results will appear here when a connected data source returns evidence. CPGist will keep the answer traceable to its source, filters, and calculation.</p></article><article className="rounded-2xl border border-dashed border-[var(--border)] p-8 text-center"><BarChart3 className="mx-auto text-[var(--text-muted)]" size={24}/><p className="mt-3 text-sm text-[var(--text-secondary)]">No chart data available.</p></article><ChatUI initialContext={{ source: "workspace", label: "Analysis follow-up", prompt: query }}/></div><aside className="h-fit rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><span className="eyebrow">Context rail</span><dl className="mt-5 space-y-4 text-sm"><dt className="text-[var(--text-muted)]">Data source</dt><dd>Connected sources</dd><dt className="text-[var(--text-muted)]">Date range</dt><dd>Not selected</dd><dt className="text-[var(--text-muted)]">Freshness</dt><dd className="text-[var(--success)]">Awaiting data</dd></dl></aside></div></section> }
function Workflows({ assign }: { assign: (text?: string) => void }) { return <section className="mx-auto max-w-5xl"><span className="eyebrow">Workflow library</span><h1 className="mt-3 font-serif text-5xl">Assign repeatable work.</h1><p className="mt-4 max-w-xl text-[var(--text-secondary)]">Start with a focused analytical workflow, then adjust its context before running it against connected data.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{workflowCards.map((card) => <button key={card.title} onClick={() => assign(card.title)} className="group rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 text-left hover:-translate-y-1 hover:border-[var(--accent)]"><div className="flex items-start justify-between"><Sparkles size={18} className="text-[var(--accent)]"/><ChevronRight size={17} className="text-[var(--text-muted)] group-hover:translate-x-1"/></div><h2 className="mt-8 font-semibold">{card.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">{card.detail}</p></button>)}</div></section> }
function Placeholder({ view, go, alerts }: { view: View; go: (v: View) => void; alerts: number }) { const copy: Record<View, string> = { Insights: "Insights aggregate real findings from completed analyses.", Alerts: alerts ? `${alerts} unread alerts from connected data.` : "No alerts available from connected data.", Reports: "Build executive-ready reports from analysis blocks.", Data: "Review connected brands, categories, retailers, products, sales, promotions, and distribution.", Settings: "Control workspace preferences, audience framing, and data connections.", Dashboard: "", Analyses: "", Workflows: "" }; return <section className="mx-auto max-w-5xl"><span className="eyebrow">{view}</span><h1 className="mt-3 font-serif text-5xl">{view === "Alerts" ? "What requires attention?" : view === "Insights" ? "Signals worth exploring." : view}</h1><p className="mt-4 max-w-xl text-[var(--text-secondary)]">{copy[view]}</p><div className="mt-10 rounded-2xl border border-dashed border-[var(--border)] p-10 text-center"><Check className="mx-auto text-[var(--success)]" size={22}/><p className="mt-3 text-sm text-[var(--text-secondary)]">No records available yet.</p><button onClick={() => go("Dashboard")} className="mt-5 rounded-lg bg-[var(--accent)] px-3 py-2 text-xs font-semibold text-[var(--background)]">Assign an analysis</button></div></section> }

export default CPGistWorkspace;
