import { NextRequest, NextResponse } from "next/server";
import React from "react";
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export const runtime = "nodejs";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: "Helvetica" },
  title: { fontSize: 20, marginBottom: 4, fontWeight: 700 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 20 },
  sectionHeading: { fontSize: 13, fontWeight: 700, marginTop: 16, marginBottom: 6 },
  narrative: { lineHeight: 1.5 },
  recItem: { marginBottom: 4 },
  traceItem: { fontSize: 9, color: "#555", marginBottom: 2 },
});

interface ExportBody {
  title?: string;
  narrative: string;
  recommendations?: string[];
  sourceTrace?: { tool: string; args: Record<string, unknown>; source_tables: string[] }[];
}

// Renders a one-page "insight deck" PDF: narrative + recommendations +
// the sourceTrace explainability footer. Chart images can be added later
// by passing a base64 PNG (e.g. captured client-side via html-to-image)
// and rendering it with <Image src={...} /> below the narrative.
function InsightDeck({ title, narrative, recommendations, sourceTrace }: ExportBody) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title ?? "CPGist Insight"}</Text>
        <Text style={styles.subtitle}>Generated by CPGist — synthetic CPG data, not licensed syndicated data</Text>

        <Text style={styles.sectionHeading}>Narrative</Text>
        <Text style={styles.narrative}>{narrative}</Text>

        {recommendations && recommendations.length > 0 && (
          <>
            <Text style={styles.sectionHeading}>Recommended Actions</Text>
            {recommendations.map((rec, i) => (
              <Text key={i} style={styles.recItem}>
                {i + 1}. {rec}
              </Text>
            ))}
          </>
        )}

        {sourceTrace && sourceTrace.length > 0 && (
          <>
            <Text style={styles.sectionHeading}>How this was found (source trace)</Text>
            {sourceTrace.map((t, i) => (
              <Text key={i} style={styles.traceItem}>
                {t.tool}({JSON.stringify(t.args)}) → {t.source_tables.join(", ")}
              </Text>
            ))}
          </>
        )}
      </Page>
    </Document>
  );
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as ExportBody;
    if (!body.narrative) {
      return NextResponse.json({ error: "Requires narrative." }, { status: 400 });
    }

    const buffer = await renderToBuffer(<InsightDeck {...body} />);

    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="cpgist-insight.pdf"',
      },
    });
  } catch (err: any) {
    console.error("Export PDF route error:", err);
    return NextResponse.json({ error: err?.message ?? "Unknown error" }, { status: 500 });
  }
}
