create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  org_id bigint not null default 1
);
create table if not exists public.retailers (
  id bigint generated by default as identity primary key,
  name text not null,
  channel text not null default 'Grocery',
  region text not null default 'Global',
  total_stores integer not null default 100,
  org_id bigint not null default 1
);
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand_id bigint references public.brands(id) on delete cascade,
  name text not null,
  category text not null,
  org_id bigint not null default 1
);
create table if not exists public.sales_facts (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  retailer_id bigint references public.retailers(id) on delete cascade,
  week_ending date not null,
  dollar_sales numeric not null default 0,
  units numeric not null default 0,
  acv_distribution numeric,
  on_promo boolean not null default false,
  promo_type text,
  discount_depth_pct numeric not null default 0,
  org_id bigint not null default 1
);
create table if not exists public.insight_feedback (
  id bigint generated by default as identity primary key,
  analysis_id text,
  user_id uuid references auth.users(id) on delete set null,
  insight_summary text,
  feedback_type text,
  outcome text check (outcome in ('worked','didnt_work','unknown')),
  comment text,
  created_at timestamptz not null default now(),
  org_id bigint not null default 1
);
create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  brand_id bigint references public.brands(id) on delete cascade,
  retailer_id bigint references public.retailers(id) on delete cascade,
  category text not null default 'General',
  region text,
  alert_type text not null default 'velocity_swing_down',
  week_ending date not null default current_date,
  baseline_units numeric,
  actual_units numeric,
  swing_pct numeric,
  title text,
  description text,
  narrative text,
  severity text not null default 'info',
  status text not null default 'open',
  related_entity_id text,
  created_at timestamptz not null default now(),
  org_id bigint not null default 1,
  unique (brand_id, retailer_id, week_ending, alert_type)
);

alter table public.insight_feedback add column if not exists analysis_id text;
alter table public.insight_feedback add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.insight_feedback add column if not exists feedback_type text;
alter table public.insight_feedback add column if not exists comment text;
alter table public.insight_feedback add column if not exists org_id bigint not null default 1;
alter table public.alerts add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.alerts add column if not exists title text;
alter table public.alerts add column if not exists description text;
alter table public.alerts add column if not exists severity text not null default 'info';
alter table public.alerts add column if not exists status text not null default 'open';
alter table public.alerts add column if not exists related_entity_id text;
alter table public.alerts add column if not exists org_id bigint not null default 1;

create or replace view public.v_brand_share with (security_invoker = true) as
with brand_week as (
  select b.id as brand_id, b.name as brand_name, b.category, sf.retailer_id, sf.week_ending,
    sum(sf.dollar_sales) as brand_dollar_sales
  from public.sales_facts sf join public.products p on p.id = sf.product_id join public.brands b on b.id = p.brand_id
  group by b.id, b.name, b.category, sf.retailer_id, sf.week_ending
), category_week as (
  select b.category, sf.retailer_id, sf.week_ending, sum(sf.dollar_sales) as category_dollar_sales
  from public.sales_facts sf join public.products p on p.id = sf.product_id join public.brands b on b.id = p.brand_id
  group by b.category, sf.retailer_id, sf.week_ending
)
select bw.brand_id, bw.brand_name, bw.category, bw.retailer_id, r.name as retailer_name, r.channel, r.region,
  bw.week_ending, bw.brand_dollar_sales, cw.category_dollar_sales,
  case when cw.category_dollar_sales > 0 then round((bw.brand_dollar_sales / cw.category_dollar_sales) * 100, 2) end as brand_share_pct
from brand_week bw join category_week cw using (category, retailer_id, week_ending) join public.retailers r on r.id = bw.retailer_id;

create or replace view public.v_promo_lift with (security_invoker = true) as
with base as (
  select sf.*, avg(case when not sf.on_promo then sf.units end) over (partition by sf.product_id, sf.retailer_id order by sf.week_ending rows between 4 preceding and 1 preceding) as trailing_nonpromo_baseline_units
  from public.sales_facts sf
)
select b.product_id, p.name as product_name, p.brand_id, br.name as brand_name, b.retailer_id, r.name as retailer_name,
  r.channel, r.region, b.week_ending, b.promo_type, b.discount_depth_pct, b.units as promo_week_units,
  b.trailing_nonpromo_baseline_units,
  case when b.trailing_nonpromo_baseline_units > 0 then round(((b.units - b.trailing_nonpromo_baseline_units) / b.trailing_nonpromo_baseline_units) * 100, 1) end as pct_lift,
  p.category
from base b join public.products p on p.id = b.product_id join public.brands br on br.id = p.brand_id join public.retailers r on r.id = b.retailer_id
where b.on_promo = true;

alter table public.brands enable row level security;
alter table public.retailers enable row level security;
alter table public.products enable row level security;
alter table public.sales_facts enable row level security;
alter table public.alerts enable row level security;
alter table public.insight_feedback enable row level security;

do $$ begin
  execute 'drop policy if exists cpgist_demo_read on public.brands';
  execute 'create policy cpgist_demo_read on public.brands for select to authenticated using (org_id = 1)';
  execute 'drop policy if exists cpgist_demo_read on public.retailers';
  execute 'create policy cpgist_demo_read on public.retailers for select to authenticated using (org_id = 1)';
  execute 'drop policy if exists cpgist_demo_read on public.products';
  execute 'create policy cpgist_demo_read on public.products for select to authenticated using (org_id = 1)';
  execute 'drop policy if exists cpgist_demo_read on public.sales_facts';
  execute 'create policy cpgist_demo_read on public.sales_facts for select to authenticated using (org_id = 1)';
  execute 'drop policy if exists cpgist_alerts_read on public.alerts';
  execute 'create policy cpgist_alerts_read on public.alerts for select to authenticated using (org_id = 1 and (user_id is null or user_id = auth.uid()))';
  execute 'drop policy if exists cpgist_feedback_insert on public.insight_feedback';
  execute 'create policy cpgist_feedback_insert on public.insight_feedback for insert to authenticated with check (org_id = 1 and (user_id is null or user_id = auth.uid()))';
end $$;

grant select on public.brands, public.retailers, public.products, public.sales_facts, public.v_brand_share, public.v_promo_lift to authenticated;
grant select on public.alerts to authenticated;
grant select, insert on public.insight_feedback to authenticated;
grant usage, select on all sequences in schema public to authenticated;
